# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

###### k8s NODE 3~4 #####

  config.vm.define "k8s-node3" do |cfg|
    cfg.vm.box = "generic/centos7"
    cfg.vm.host_name = "k8s-node3"
    cfg.vm.network :public_network, :dev => "vswitch01", :ovs => true
    cfg.vm.network "private_network", ip: "172.16.1.13"
    cfg.vm.network "forwarded_port", guest: 22, host: 60013, auto_correct: true, id: "ssh"
    cfg.vm.provision "shell", inline: "mkdir /root/.ssh",privileged: true
    cfg.vm.provision "file", source: "authorized_keys", destination: "authorized_keys"
    cfg.vm.provision "shell", inline: "cat authorized_keys >> /root/.ssh/authorized_keys"
    cfg.vm.provider :libvirt do |resource|
      resource.memory = 1024
      resource.cpus = 1
      end
    end

  config.vm.define "k8s-node4" do |cfg|
    cfg.vm.box = "generic/centos7"
    cfg.vm.host_name = "k8s-node4"
    cfg.vm.network :public_network, :dev => "vswitch01", :ovs => true
    cfg.vm.network "private_network", ip: "172.16.1.14"
    cfg.vm.network "forwarded_port", guest: 22, host: 60014, auto_correct: true, id: 'ssh'
    cfg.vm.provision "shell", inline: "mkdir /root/.ssh",privileged: true
    cfg.vm.provision "file", source: "authorized_keys", destination: "authorized_keys"
    cfg.vm.provision "shell", inline: "cat authorized_keys >> /root/.ssh/authorized_keys"
    cfg.vm.provider :libvirt do |resource|
      resource.memory = 2048
      resource.cpus = 2
    end
  end
end

