---
- name: Create Web Service for MOON
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: create a namespace for MOON
      k8s:
        name: moon
        api_version: v1
        kind: Namespace
        state: present
        
    - name: MAIN deploy and svc for MOON
      k8s:
        state: present
        src: /var/lib/jenkins/workspace/webhook-k8s/moon/web/deploy-main-moon.yaml

    - name: SHOP deploy and svc for MOON
      k8s:
        state: present
        src: /var/lib/jenkins/workspace/webhook-k8s/moon/web/deploy-shop-moon.yaml

    - name: FINANCE deploy and svc for MOON
      k8s:
        state: present
        src: /var/lib/jenkins/workspace/webhook-k8s/moon/web/deploy-finance-moon.yaml

    - name: Ingress for MOON
      k8s:
        state: present
        src: /var/lib/jenkins/workspace/webhook-k8s/moon/web/ingress-moon.yaml
