---
- name: Build an image and push it to a private repo FOR MOON
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: main image FOR MOON
      docker_image:
        build:
          path: /var/lib/jenkins/workspace/webhook-k8s/moon/web/main
        name: 211.183.3.199:5000/main-moon
        tag: 1.0
        push: yes
        source: build

    - name: shop image FOR MOON
      docker_image:
        build:
          path: /var/lib/jenkins/workspace/webhook-k8s/moon/web/shop
        name: 211.183.3.199:5000/shop-moon
        tag: 1.0
        push: yes
        source: build

    - name: finance image FOR MOON
      docker_image:
        build:
          path: /var/lib/jenkins/workspace/webhook-k8s/moon/web/finance
        name: 211.183.3.199:5000/finance-moon
        tag: 1.0
        push: yes
        source: build
